### ISSUE TITLE
Add static typing to CI

### ISSUE THREAD

**Issue by TomAugspurger** [stac-utils/stac-geoparquet#41]
Add configuration for mypy (disallow untyped defs in this repo) and get this running in CI.

**Comment by kylebarron** [comment]
There's already a mypy hook in pre-commit-config:
https://github.com/stac-utils/stac-geoparquet/blob/50f2886b7d8acfe5053c936f42c6240c0aecb3d7/.pre-commit-config.yaml#L21-L37

I generally dislike putting the mypy check in pre-commit because it doesn't have access to any dependencies, or, in this case, you have to re-define dependencies (and I assume that anything listed in `additional_dependencies` is not constrained to the same versions in any other lockfile)

**Comment by TomAugspurger** [comment]
Ah right, forgot about that.

I agree with moving it out of pre-commit now that this is growing a bit.

**Comment by TomAugspurger** [comment]
Closed by #44
